export const  futuresTickers = [
  { label: 'E-mini S&P 500 Futures', year: 'ES' },
  { label: 'E-mini Nasdaq 100 Futures', year: 'NQ' },
  { label: 'E-mini Dow Jones Futures', year: 'YM' },
  { label: 'Crude Oil Futures', year: 'CL' },
  { label: 'Gold Futures', year: 'GC' },
  { label: 'Silver Futures', year: 'SI' },
  { label: 'Natural Gas Futures', year: 'NG' },
  { label: 'Euro FX Futures', year: '6E' },
  { label: 'British Pound Futures', year: '6B' },
  { label: 'Japanese Yen Futures', year: '6J' },
  { label: 'Eurodollar Futures', year: 'GE' },
  { label: 'Treasury Bond Futures', year: 'ZB' },
  { label: '10-Year Treasury Note Futures', year: 'ZN' },
  { label: '5-Year Treasury Note Futures', year: 'ZF' },
  { label: 'S&P 500 E-Mini Futures', year: 'SP' },
  { label: 'Russell 2000 E-Mini Futures', year: 'RTY' },
  { label: 'Australian Dollar Futures', year: '6A' },
  { label: 'Canadian Dollar Futures', year: '6C' },
  { label: 'Cocoa Futures', year: 'CC' },
  { label: 'Coffee Futures', year: 'KC' },
  { label: 'Apple Inc.', year: 'AAPL' },
  { label: 'Microsoft Corporation', year: 'MSFT' },
  { label: 'Amazon.com Inc.', year: 'AMZN' },
  { label: 'Alphabet Inc. (Google)', year: 'GOOGL' },
  { label: 'Facebook Inc.', year: 'FB' },
  { label: 'Tesla Inc.', year: 'TSLA' },
  { label: 'Walmart Inc.', year: 'WMT' },
  { label: 'Johnson & Johnson', year: 'JNJ' },
  { label: 'Visa Inc.', year: 'V' },
  { label: 'JPMorgan Chase & Co.', year: 'JPM' },
  { label: 'Procter & Gamble Company', year: 'PG' },
  { label: 'Bank of America Corporation', year: 'BAC' },
  { label: 'Coca-Cola Company', year: 'KO' },
  { label: 'Walt Disney Company', year: 'DIS' },
  { label: 'Netflix Inc.', year: 'NFLX' },
  { label: 'Intel Corporation', year: 'INTC' },
  { label: 'IBM', year: 'IBM' },
  { label: 'McDonald\'s Corporation', year: 'MCD' },
  { label: 'General Electric Company', year: 'GE' },
  { label: 'Cisco Systems Inc.', year: 'CSCO' },
  { label: 'AT&T Inc.', year: 'T' },
  { label: 'Verizon Communications Inc.', year: 'VZ' },
  { label: 'Exxon Mobil Corporation', year: 'XOM' },
  { label: 'Chevron Corporation', year: 'CVX' },
  { label: 'Johnson Controls International plc', year: 'JCI' },
  { label: 'Mastercard Incorporated', year: 'MA' },
  { label: 'Pfizer Inc.', year: 'PFE' },
  { label: 'General Motors Company', year: 'GM' },
  { label: 'Ford Motor Company', year: 'F' },
  { label: 'American Express Company', year: 'AXP' },
  { label: 'The Home Depot Inc.', year: 'HD' },
  { label: 'Visa Inc.', year: 'V' },
  { label: 'Boeing Company', year: 'BA' },
  { label: 'Oracle Corporation', year: 'ORCL' },
  { label: 'Adobe Inc.', year: 'ADBE' },
  { label: 'Salesforce.com Inc.', year: 'CRM' },
  { label: 'Starbucks Corporation', year: 'SBUX' },
  { label: 'NVIDIA Corporation', year: 'NVDA' },
  { label: 'PayPal Holdings Inc.', year: 'PYPL' },
  { label: 'Snap Inc.', year: 'SNAP' },
  { label: 'Zoom Video Communications Inc.', year: 'ZM' },
  { label: 'Square Inc.', year: 'SQ' },
  { label: 'Moderna Inc.', year: 'MRNA' },
  { label: 'Beyond Meat Inc.', year: 'BYND' },
  { label: 'GameStop Corp.', year: 'GME' },
  { label: 'Palantir Technologies Inc.', year: 'PLTR' },
  { label: 'Snowflake Inc.', year: 'SNOW' },
  { label: 'Coinbase Global Inc.', year: 'COIN' },
  { label: 'Airbnb Inc.', year: 'ABNB' },
  { label: 'Roblox Corporation', year: 'RBLX' },
  { label: 'DoorDash Inc.', year: 'DASH' },
  { label: 'Unity Software Inc.', year: 'U' },
  { label: 'Snowflake Inc.', year: 'SNOW' },
  { label: 'Affirm Holdings Inc.', year: 'AFRM' },
  { label: 'Etsy Inc.', year: 'ETSY' },
  { label: 'Wayfair Inc.', year: 'W' },
  { label: 'DocuSign Inc.', year: 'DOCU' },
  { label: 'Twilio Inc.', year: 'TWLO' },
  { label: 'Roblox Corporation', year: 'RBLX' },
  { label: 'Virgin Galactic Holdings Inc.', year: 'SPCE' },
  { label: 'Coinbase Global Inc.', year: 'COIN' },
  { label: 'Peloton Interactive Inc.', year: 'PTON' },
  { label: 'Virgin Galactic Holdings Inc.', year: 'SPCE' },
  { label: 'Workhorse Group Inc.', year: 'WKHS' },
  { label: 'Fisker Inc.', year: 'FSR' },
  { label: 'Nikola Corporation', year: 'NKLA' },
  { label: 'GoPro Inc.', year: 'GPRO' },
  { label: 'Pinterest Inc.', year: 'PINS' },
  { label: 'Zynga Inc.', year: 'ZNGA' },
  { label: 'GoPro Inc.', year: 'GPRO' },
  { label: 'Bitcoin Futures', year: 'BTC' },
  { label: 'Ethereum Futures', year: 'ETH' },
  { label: 'Litecoin Futures', year: 'LTC' },
  { label: 'Ripple Futures', year: 'XRP' },
  { label: 'Bitcoin Cash Futures', year: 'BCH' },
  { label: 'Cardano Futures', year: 'ADA' },
  { label: 'Polkadot Futures', year: 'DOT' },
  { label: 'Chainlink Futures', year: 'LINK' },
  { label: 'Stellar Futures', year: 'XLM' },
  { label: 'Dogecoin Futures', year: 'DOGE' },
  { label: 'VeChain Futures', year: 'VET' },
  { label: 'Filecoin Futures', year: 'FIL' },
  { label: 'Tron Futures', year: 'TRX' },
  { label: 'Monero Futures', year: 'XMR' },
  { label: 'EOS Futures', year: 'EOS' },
  { label: 'Neo Futures', year: 'NEO' },
  { label: 'IOTA Futures', year: 'MIOTA' },
  { label: 'Tezos Futures', year: 'XTZ' },
  { label: 'Cosmos Futures', year: 'ATOM' },
  { label: 'NEM Futures', year: 'XEM' },
  { label: 'Aave Futures', year: 'AAVE' },
  { label: 'Compound Futures', year: 'COMP' },
  { label: 'Synthetix Futures', year: 'SNX' },
  { label: 'Yearn.finance Futures', year: 'YFI' },
  { label: 'UMA Futures', year: 'UMA' },
  { label: 'Maker Futures', year: 'MKR' },
  { label: 'Bitcoin SV Futures', year: 'BSV' },
  { label: 'Theta Futures', year: 'THETA' },
  { label: 'Dai Futures', year: 'DAI' },
  { label: 'Zcash Futures', year: 'ZEC' },
  { label: 'Kusama Futures', year: 'KSM' },
  { label: 'BitTorrent Futures', year: 'BTT' },
  { label: 'Huobi Token Futures', year: 'HT' },
  { label: 'NEAR Protocol Futures', year: 'NEAR' },
  { label: 'Decred Futures', year: 'DCR' },
  { label: 'Compound USDT Futures', year: 'CUSDT' },
  { label: 'Avalanche Futures', year: 'AVAX' },
  { label: 'Elrond Futures', year: 'EGLD' },
  { label: 'SushiSwap Futures', year: 'SUSHI' },
  { label: 'Bitcoin Gold Futures', year: 'BTG' },
  { label: 'Dash Futures', year: 'DASH' },
  { label: 'Ontology Futures', year: 'ONT' },
  { label: 'Ethereum Classic Futures', year: 'ETC' },
  { label: 'NEO Futures', year: 'NEO' },
  { label: 'Celsius Futures', year: 'CEL' },
  { label: 'KuCoin Token Futures', year: 'KCS' },
  { label: 'Chiliz Futures', year: 'CHZ' },
  { label: 'Holo Futures', year: 'HOT' },
  { label: 'Swipe Futures', year: 'SXP' },
  { label: 'Nexo Futures', year: 'NEXO' },
  { label: 'PancakeSwap Futures', year: 'CAKE' },
  { label: 'Enjin Coin Futures', year: 'ENJ' },
  { label: 'Polygon Futures', year: 'MATIC' },
  { label: 'Voyager Token Futures', year: 'VGX' },
  { label: 'The Graph Futures', year: 'GRT' },
  { label: 'Quant Futures', year: 'QNT' },
  { label: 'REN Futures', year: 'REN' },
  { label: 'Algorand Futures', year: 'ALGO' },
  { label: 'Zilliqa Futures', year: 'ZIL' },
  { label: 'Celo Futures', year: 'CELO' },
  { label: 'Synthetix Futures', year: 'SNX' },
  { label: '0x Futures', year: 'ZRX' },
  { label: 'IoTeX Futures', year: 'IOTX' },
  { label: 'Loopring Futures', year: 'LRC' },
  { label: 'Waves Futures', year: 'WAVES' },
  { label: 'StakeHound Staked Ether Futures', year: 'STETH' },
  { label: 'Lido Staked Ether Futures', year: 'STETH' },
  { label: 'Horizen Futures', year: 'ZEN' },
  { label: 'Ocean Protocol Futures', year: 'OCEAN' },
  { label: 'Reserve Rights Futures', year: 'RSR' },
  { label: 'Balancer Futures', year: 'BAL' },
  { label: 'OKB Futures', year: 'OKB' },
  ];
  