// -------------------------------------------- select options tickers appear in manual add trade --------------------------------------------------
export const tickerArrays = [
  [
    { label: 'E-mini S&P 500 Futures', year: 'ES' },
    { label: 'E-mini Nasdaq 100 Futures', year: 'NQ' },
    { label: 'E-mini Dow Jones Futures', year: 'YM' },
    { label: 'Crude Oil Futures', year: 'CL' },
    { label: 'Gold Futures', year: 'GC' },
    { label: 'Silver Futures', year: 'SI' },
    { label: 'Natural Gas Futures', year: 'NG' },
    { label: 'Euro FX Futures', year: '6E' },
    { label: 'British Pound Futures', year: '6B' },
    { label: 'Japanese Yen Futures', year: '6J' },
    { label: 'Eurodollar Futures', year: 'GE' },
    { label: 'Treasury Bond Futures', year: 'ZB' },
    { label: '10-Year Treasury Note Futures', year: 'ZN' },
    { label: '5-Year Treasury Note Futures', year: 'ZF' },
    { label: 'S&P 500 E-Mini Futures', year: 'SP' },
    { label: 'Russell 2000 E-Mini Futures', year: 'RTY' },
    { label: 'Australian Dollar Futures', year: '6A' },
    { label: 'Canadian Dollar Futures', year: '6C' },
    { label: 'Cocoa Futures', year: 'CC' },
    { label: 'Coffee Futures', year: 'KC' }
  ],
  [
    { label: 'Apple Inc.', year: 'AAPL' },
    { label: 'Microsoft Corporation', year: 'MSFT' },
    { label: 'Amazon.com Inc.', year: 'AMZN' },
    { label: 'Alphabet Inc. (Google)', year: 'GOOGL' },
    { label: 'Facebook Inc.', year: 'FB' },
    { label: 'Tesla Inc.', year: 'TSLA' },
    { label: 'NVIDIA Corporation', year: 'NVDA' },
    { label: 'Netflix Inc.', year: 'NFLX' },
    { label: 'PayPal Holdings Inc.', year: 'PYPL' },
    { label: 'Visa Inc.', year: 'V' },
    { label: 'Mastercard Incorporated', year: 'MA' },
    { label: 'JPMorgan Chase & Co.', year: 'JPM' },
    { label: 'Bank of America Corporation', year: 'BAC' },
    { label: 'Walmart Inc.', year: 'WMT' },
    { label: 'Johnson & Johnson', year: 'JNJ' },
    { label: 'Procter & Gamble Company', year: 'PG' },
    { label: 'Verizon Communications Inc.', year: 'VZ' },
    { label: 'AT&T Inc.', year: 'T' },
    { label: 'Intel Corporation', year: 'INTC' },
    { label: 'Cisco Systems Inc.', year: 'CSCO' },
    { label: 'Coca-Cola Company', year: 'KO' },
    { label: 'Pfizer Inc.', year: 'PFE' },
    { label: 'Walt Disney Company', year: 'DIS' },
    { label: 'McDonald\'s Corporation', year: 'MCD' },
    { label: 'General Electric Company', year: 'GE' },
    { label: 'IBM', year: 'IBM' },
    // Add more stock tickers below
    { label: 'Visa Inc.', year: 'V' },
    { label: 'Johnson & Johnson', year: 'JNJ' },
    { label: 'Walmart Inc.', year: 'WMT' },
    { label: 'The Home Depot Inc.', year: 'HD' },
    { label: 'Intel Corporation', year: 'INTC' },
    // ... continue adding more stock tickers as needed
  ],
  [
    { label: 'Bitcoin', year: 'BTC' },
    { label: 'Ethereum', year: 'ETH' },
    { label: 'Binance Coin', year: 'BNB' },
    { label: 'Cardano', year: 'ADA' },
    { label: 'XRP', year: 'XRP' },
    { label: 'Solana', year: 'SOL' },
    { label: 'Polkadot', year: 'DOT' },
    { label: 'Dogecoin', year: 'DOGE' },
    { label: 'Avalanche', year: 'AVAX' },
    { label: 'Terra', year: 'LUNA' },
    // ... (previous entries)
    { label: 'VeChain', year: 'VET' },
    { label: 'Chainlink', year: 'LINK' },
    { label: 'Litecoin', year: 'LTC' },
    { label: 'Cosmos', year: 'ATOM' },
    { label: 'Bitcoin Cash', year: 'BCH' },
    { label: 'Filecoin', year: 'FIL' },
    // ... (previous entries)
    { label: 'Tezos', year: 'XTZ' },
    { label: 'Stellar', year: 'XLM' },
    { label: 'Aave', year: 'AAVE' },
    { label: 'Compound', year: 'COMP' },
    { label: 'Synthetix', year: 'SNX' },
    { label: 'Polygon', year: 'MATIC' },
    { label: 'Algorand', year: 'ALGO' },
    // ... (previous entries)
    { label: 'Neo', year: 'NEO' },
    { label: 'Ethereum Classic', year: 'ETC' },
    { label: 'Dash', year: 'DASH' },
    { label: 'Zcash', year: 'ZEC' },
    { label: 'Monero', year: 'XMR' },
    { label: 'IOTA', year: 'MIOTA' },
    { label: 'Theta', year: 'THETA' },
    // ... (previous entries)
    { label: 'NEM', year: 'XEM' },
    { label: 'EOS', year: 'EOS' },
    { label: 'Tron', year: 'TRX' },
    { label: 'VeThor Token', year: 'VTHO' },
    { label: 'Kusama', year: 'KSM' },
    { label: 'BitTorrent', year: 'BTT' },
    { label: 'Huobi Token', year: 'HT' },
    // ... (previous entries)
    { label: 'Decentraland', year: 'MANA' },
    { label: 'Zilliqa', year: 'ZIL' },
    { label: 'DigiByte', year: 'DGB' },
    { label: 'OMG Network', year: 'OMG' },
    { label: 'Waves', year: 'WAVES' },
    { label: 'Celo', year: 'CELO' },
    { label: 'Klaytn', year: 'KLAY' },
    // ... (previous entries)
    { label: 'SushiSwap', year: 'SUSHI' },
    { label: 'Maker', year: 'MKR' },
    { label: 'Ren', year: 'REN' },
    { label: 'Chiliz', year: 'CHZ' },
    { label: 'Curve DAO Token', year: 'CRV' },
    { label: 'Siacoin', year: 'SC' },
    { label: 'Ontology', year: 'ONT' },
    // ... (previous entries)
    { label: 'Synereo', year: 'AMP' },
    { label: 'Golem', year: 'GLM' },
    { label: 'Reserve Rights', year: 'RSR' },
    { label: '0x', year: 'ZRX' },
    { label: 'Horizen', year: 'ZEN' },
    { label: 'Enjin Coin', year: 'ENJ' },
    { label: 'Holo', year: 'HOT' },
    // ... (add more crypto names and symbols)
  ]
  
];



